sudo: required
dist: xenial

language: java

before_script:
  - sudo -H apt-get update
  - sudo -H apt-get install -y maven python3 python3-setuptools python3-pip
  - sudo -H pip3 install --upgrade setuptools wheel virtualenv
  - sudo -H pip3 install $TRAVIS_BUILD_DIR/emulator
  - sudo -H pip3 install $TRAVIS_BUILD_DIR/python-package
  - cd $TRAVIS_BUILD_DIR && cd java-package/brainflow && mvn package

script:
  - sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cython_linux.py python3 $TRAVIS_BUILD_DIR/tests/python/brainflow_get_data.py
  - cd $TRAVIS_BUILD_DIR/tests/java/ && sudo -H javac -classpath $TRAVIS_BUILD_DIR/java-package/brainflow/target/brainflow-java-jar-with-dependencies.jar BrainFlowTest.java && sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cython_linux.py java -classpath .;$TRAVIS_BUILD_DIR/java-package/brainflow/target/brainflow-java-jar-with-dependencies.jar BrainFlowTest

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
