image:
- Visual Studio 2015

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 3

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- pip install .\emulator\
- pip install .\python-package
- ps: Restart-Computer -Force
- ps: .\emulator\brainflow_emulator\com0com\certmgr.exe  /add .\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine root
- ps: .\emulator\brainflow_emulator\com0com\certmgr.exe /add .\emulator\brainflow_emulator\com0com\com0com.cer /s /r localMachine trustedpublisher

test_script:
- python .\emulator\brainflow_emulator\cython_windows.py python .\tests\python\brainflow_get_data.py

notifications:
  - provider: Email
    to:
      - a1994ndrey@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
