[brainflow]
git-tree-sha1 = "3dde952ba97adbf0e12b6ec7e0a74bc20fb95a9d"
lazy = true

    [[brainflow.download]]
    sha256 = "0413d7ae12be559abd2062285c6f206891a2288ba817acc8d91aa68ccc0bbec5"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.3.2/compiled_libs.tar"
