[brainflow]
git-tree-sha1 = "551bbeee43bcecdabbac06b09"
lazy = true

    [[brainflow.download]]
    sha256 = "d8bd9247bd975ccbbaccdec4a"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/3.8.1/compiled_libs.tar"
