[brainflow]
git-tree-sha1 = "b0742f962f6e4fa0b1bfcb777ba2844d2c612ea9"
lazy = true

    [[brainflow.download]]
    sha256 = "0348cce4919c10a3850c444d0a7a66fcc5fe59c767a29d7dd1a7e5b7bb39e96c"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.0.2/compiled_libs.tar"
