[brainflow]
git-tree-sha1 = "ec1284c90901cd2a753886fba009ccb6c17db901"
lazy = true

    [[brainflow.download]]
    sha256 = "0937bebb9c4c877f9dd1ce6835b38f2d7fb78e5d6c65aceb9da70e97be51f6a2"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.2.0/compiled_libs.tar"
