[brainflow]
git-tree-sha1 = "af6efa552bc1ca9ac038d1ca4c3c02357d085ea9"
lazy = true

    [[brainflow.download]]
    sha256 = "c33796102f8fb3d8506d09eb6eff724bbe3c50cdca2b209e72c367f5218009b6"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.1.0/compiled_libs.tar"
