[brainflow]
git-tree-sha1 = "2dc6ed5f9f4403b01ef49a72db1be074ed27eeab"
lazy = true

    [[brainflow.download]]
    sha256 = "67e149ace85e340dd6e5acd166714491ed05220f517e016da5c8d8b25f4afe25"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.3.1/compiled_libs.tar"
