[brainflow]
git-tree-sha1 = "a8daed007df7094dfa0a6e765b6d3af1d809929c"
lazy = true

    [[brainflow.download]]
    sha256 = "761509e60bc00117d0c9dd44cce85bce70cf6a42cc89c53bf85f97bb7cf57cf7"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.5.0/compiled_libs.tar"
