[brainflow]
git-tree-sha1 = "ea057f28faf163334c735efba1128cae295cb032"
lazy = true

    [[brainflow.download]]
    sha256 = "91cd2f2a91d6c0f790db63cde4e54b950844e58f9c09ad601431d1e1956b63fb"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.7.0/compiled_libs.tar"
