[brainflow]
git-tree-sha1 = "d8246efb4570a6abb28dc2871aad6c6fea3b2656"
lazy = true

    [[brainflow.download]]
    sha256 = "988eef1d1ca44885e97205a8ae75c7818ff9f88a06aa29cc010f279be6ae6e9d"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.6.1/compiled_libs.tar"
