[brainflow]
git-tree-sha1 = "1e3ec07a972e8a454a8fdba8812db30df2a37642"
lazy = true

    [[brainflow.download]]
    sha256 = "1e181289d0d53c8b91acefc15cd1d064feab7a5c66c98c6a1db34485aa8157b1"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.8.1/compiled_libs.tar"
