[brainflow]
git-tree-sha1 = "cc8e836104c73c93a47770c3adcc9f740f761df8"
lazy = true

    [[brainflow.download]]
    sha256 = "eceec3d8575b063ad677ef0f9a83c636163f2eb53e5f7d25b1d6eaa389c73b77"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.8.0/compiled_libs.tar"
