[brainflow]
git-tree-sha1 = "cc1db5a97cb3853d3e25bcceb8840e08ff265bd2"
lazy = true

    [[brainflow.download]]
    sha256 = "2a4246ba996f930e833c7c843323f1dc103dae85390399fe1d6d4a94bb25c54f"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.1.2/compiled_libs.tar"
