name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to BrainFlow project and thanks for your contribution! We will try to fix your issue ASAP. Make sure that you\'ve read https://brainflow.readthedocs.io/en/latest/AskHelp.html#issue-format'
        pr-message: 'Welcome to BrainFlow project and thanks for your contribution! We will try to review your PR ASAP. Make sure that you\'ve read https://brainflow.readthedocs.io/en/latest/BrainFlowDev.html#pull-requests' 
